### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by emayerhofer** [carlaml/LDpred-funct#11]
Hello,
for some reason, if the last SNP in the SS file is included in the score, there is an index out of bounds error. 

> Traceback (most recent call last):
>   File "LDpred-funct/ldpredfunct.py", line 234, in <module>
>     main()
>   File "LDpred-funct/ldpredfunct.py", line 181, in main
>     method="STANDARD_FUNCT", skip_ambiguous=p_dict['skip_ambiguous'])
>   File "LDpred-funct/coord_genotypes_ldpredfunct_v1_2.py", line 595, in coordinate_genot_ss
>     ss_flips = ss_flips[ok_indices['ss']]  ### record flips
> IndexError: index 174814 is out of bounds for axis 0 with size 174814

I have a quick workaround, but this doesn't solve the problem:
```

--- a/coord_genotypes_ldpredfunct_v1_2.py
+++ b/coord_genotypes_ldpredfunct_v1_2.py
@@ -564,9 +564,12 @@ def coordinate_genot_ss(genotype_filename=None,
                         continue
 
             # everything seems ok.
-            ok_indices['g'].append(g_i)
-            ok_indices['ss'].append(ss_i)
-            ok_nts.append(g_nt)
+            if ss_i < len(ss_indices):
+                ok_indices['ss'].append(ss_i)
+                ok_indices['g'].append(g_i)
+                ok_nts.append(g_nt)
+            else:
+                print "Skipping SNP because of index error"
 


```

**Comment by emosyne** [comment]
Hello,
I seem to have the same issue:
```
Traceback (most recent call last):
  File "../LDpred-funct/ldpredfunct.py", line 234, in <module>
    main()
  File "../LDpred-funct/ldpredfunct.py", line 181, in main
    method="STANDARD_FUNCT", skip_ambiguous=p_dict['skip_ambiguous'])
  File "/mnt/storage/emanuele/LDpred-funct/coord_genotypes_ldpredfunct_v1_2.py", line 594, in coordinate_genot_ss
    ss_flips = ss_flips[ok_indices['ss']]  ### record flips
IndexError: index 19319 is out of bounds for axis 0 with size 19319
```
This does not happen with the test files, but if I substitute the test_functfile.txt  with my function file, this error appears, and there is no progress.
Any ideas on what could be causing it?
I have checked and the funct file format is exactly the same.
Many thanks.
Emanuele

**Comment by emosyne** [comment]
I believe I have found the problem. 
Chr 6 and 7 of the test plink files have errors, if you delete these (LDpred-funct/test/TSI_6 and 7) it works.
